pipeline {
    agent any

    stages {
        stage('Checkout FastAPI Code') {
            steps {
                // FastAPI 코드가 있는 브랜치로 체크아웃
                checkout([$class: 'GitSCM', branches: [[name: 'fastapi']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'fsddcx8624', url: 'https://lab.ssafy.com/s09-fintech-finance-sub2/S09P22B207']]])
            }
        }
        
        stage('FastAPI Build and Docker Image') {
            steps {
                dir('FastAPI') {
                    sh '''
                    echo 'Building FastAPI application'
                    export PATH="/usr/bin/pip3"  # 파이썬 바이너리 경로 추가
                    pip install -r requirements.txt
                    uvicorn scr.main:app --host 0.0.0.0 --port 8000
                    '''
                    
                    echo 'Building Docker image'
                    script {
                        docker.withRegistry('', 'docker-hub-credentials') {
                            def customImage = docker.build('fastapi-app:latest', '.')
                            customImage.push()
                        }
                    }
                }
            }
        }

        stage('Deploy FastAPI') {
            steps {
                script {
                    def containerExists = sh(script: 'docker ps -a --format "{{.Names}}" | grep -q "fastapi"', returnStatus: true)
                    if (containerExists == 0) {
                        sh 'docker stop fastapi'
                        sh 'docker rm fastapi'
                    }
                    sh 'docker run -d -p 8000:8000 --name fastapi fastapi-app:latest'
                }
            }
        }
    }
}
